// <auto-generated />
using API_FARM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_FARM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007021522_MigrationsSeeders")]
    partial class MigrationsSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_FARM.Models.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("animal_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet",
                            Name = "Anna"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Consectetur adipiscing elit.",
                            Name = "John"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sed do eiusmod tempor incididunt.",
                            Name = "Michael"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet",
                            Name = "Juan"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Consectetur adipiscing elit.",
                            Name = "Vicente"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sed do eiusmod tempor incididunt.",
                            Name = "Monserrat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
